on:
  push:
    branches:
      - main
name: release-please-urp
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          path: Addons~/io.conix.arena.renderfusion-urp
          release-type: node
          package-name: release-please-action-urp
